platform :ios, "8.0"

source 'https://github.com/CocoaPods/Specs.git'
# source 'https://github.com/finventures/FinPodSpecs'

use_frameworks!

target 'FinImagePickerExample' do
    pod 'FinPhotoChooser', :path => './..'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
